name: Build mod with Gradle
on:
  push:
  # to-do: get "master" branch renamed as fabric or something else.
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get the repository contents.
      uses: actions/checkout@v3
      with:
        clean: false
    - name: What contents do we have?
      run: |
        ls -a ${{ github.workspace }}
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Attempt to compile using Gradle
      run: |
       chmod +x gradlew
       ./gradlew build
